# Generated by Django 3.2.13 on 2022-05-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='类别')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content_sample', models.CharField(max_length=50, null=True, verbose_name='内容简介')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='所属类别')),
            ],
        ),
    ]
