# Generated by Django 3.2.13 on 2022-05-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
