# Generated by Django 3.2.13 on 2022-06-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
    ]
