# Generated by Django 3.2.13 on 2022-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_blog_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数'),
        ),
    ]
