# Generated by Django 3.2.13 on 2022-05-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_blog_read_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='发布者昵称')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='web.blog', verbose_name='所属博客')),
            ],
        ),
    ]
