# Generated by Django 3.2.13 on 2022-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.FileField(default='static/blog_img/img.png', upload_to='static/blog_img/'),
        ),
    ]
